name: Benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yaml'
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.20'

      - name: setup autotools for cgo
        if: ${{ matrix.mode == 'cgo' && startsWith(matrix.os, 'macos-') }}
        run: brew install autoconf automake libtool

      - name: setup libinjection for cgo
        run: |
          wget https://github.com/libinjection/libinjection/archive/211782219663f889f471650150df12b623c5766e.tar.gz
          tar -xf 211782219663f889f471650150df12b623c5766e.tar.gz
          cd libinjection-211782219663f889f471650150df12b623c5766e
          ./autogen.sh
          ./configure
          make
          sudo make install
        working-directory: /tmp

      - run: go run mage.go benchall
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - run: go run mage.go wafbenchall
        env:
          LD_LIBRARY_PATH: /usr/local/lib

      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: build/*bench*.txt
