name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        mode:
          - cgo
          - tinygo
          - wazero
        os:
          - macos-14
          - macos-15
          - ubuntu-24.04
          - windows-2025
        exclude:
          # cgo on Windows currently fails mysteriously, same as the other wasilibs repos.
          - os: windows-2025
            mode: cgo
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: curioswitch/go-build/.github/actions/setup-go@8cee71a440fb70ec08525081efdf8088d2b3618e # v0.8.3

      - name: setup autotools for cgo (mac)
        if: ${{ matrix.mode == 'cgo' && startsWith(matrix.os, 'macos-') }}
        run: brew install autoconf automake libtool

      - name: setup libinjection for cgo
        if: ${{ matrix.mode == 'cgo' }}
        run: |-
          wget https://github.com/libinjection/libinjection/archive/211782219663f889f471650150df12b623c5766e.tar.gz
          tar -xf 211782219663f889f471650150df12b623c5766e.tar.gz
          cd libinjection-211782219663f889f471650150df12b623c5766e
          ./autogen.sh
          ./configure
          make
          sudo make install
        working-directory: /tmp

      - name: setup tinygo
        if: ${{ matrix.mode == 'tinygo' }}
        uses: acifani/setup-tinygo@dd8a7075d951a7595b2ef2123ed0ab1af0c13e56 # v3.0.0
        with:
          tinygo-version: 0.41.1
      - name: setup wasmtime for tinygo
        if: ${{ matrix.mode == 'tinygo' }}
        run: go install github.com/wasilibs/tools/cmd/wasmtime@13e21a5960c7f51cd8c92da5cf35774d3207ee38

      - name: run checks
        run: go run ./build ${{ startsWith(matrix.os, 'ubuntu-') && 'check' || 'test' }}
        env:
          LIBINJECTION_TEST_MODE: ${{ matrix.mode }}
          LD_LIBRARY_PATH: ${{ startsWith(matrix.os, 'ubuntu-') && matrix.mode == 'cgo' && '/usr/local/lib' || '' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Runs tests using wazero inside a minimal golang docker image. This makes sure the code builds
  # even when there is no C toolchain available. It is possible for code to work fine with CGO_ENABLED=0
  # but not build without a C toolchain available, e.g. if C source files are checked into the repo
  # without a build tag to exclude them from pure-Go builds.
  docker-build:
    runs-on: ubuntu-24.04
    container:
      image: golang:alpine
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - run: if command -v gcc &> /dev/null; then echo "GCC found but not expected"; exit 2; fi

      - run: go run ./build test-go
